### ISSUE TITLE
orca doesn't like 127.0.0.1

### ISSUE THREAD

**Issue by srcr** [digitalshadows/orca#2]
The shodan sub module doesn't like 127.0.0.1 and causes to break a enum run

```
Enumerating [127.0.0.1       ]:  89%|████████████████████████████████▊    | 70/79 [08:35<01:15,  8.41s/it]
Traceback (most recent call last):
  File "~/.local/bin/orca-recon", line 11, in <module>
    load_entry_point('orca-recon==0.0.1', 'console_scripts', 'orca-recon')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/export~/.local/lib/python3.6/site-packages/orca/cli/enumerate.py", line 179, in lookup_hosts_shodan
    refresh=refresh_results)
  File "/export~/.local/lib/python3.6/site-packages/orca/modules/orca_shodan.py", line 65, in shodan_lookup_ipaddr
    shodan_response = get_shodan_data(shodan_api, ipaddr)
  File "/export~/.local/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/export~/.local/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/export~/.local/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/export~/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/export~/.local/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/export~/.local/lib/python3.6/site-packages/orca/modules/orca_shodan.py", line 37, in get_shodan_data
    json_result = shodan_api.host(ipaddr)
  File "/export~/.local/lib/python3.6/site-packages/shodan/client.py", line 241, in host
    return self._request('/shodan/host/%s' % ','.join(ips), params)
  File "/export~/.local/lib/python3.6/site-packages/shodan/client.py", line 201, in _request
    raise APIError(data['error'])
shodan.exception.APIError: Invalid IP

```

**Comment by RcDS** [comment]
Added some additional validation for IP addresses. Thanks.
